spring:
  application:
    name: esbot

bot:
  token: ${BOT_TOKEN}

messages:
  defaultError: "–û–π –æ–π, —á—Ç–æ-—Ç–æ –ø–æ—à–ª–æ –Ω–µ —Ç–∞–∫! –ü–æ–ø—Ä–æ–±—É–π —Å–Ω–æ–≤–∞ –∏ –Ω–∞–ø–∏—à–∏ —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫—É - t.me/MartinHippo"
  unsupported: "–Ø –Ω–µ –∑–Ω–∞—é, —á–µ–≥–æ —Ç—ã —Ö–æ—á–µ—à—å, –Ω–æ –∫–ª—è–Ω—É—Å—å:\n–ú–µ–≥–∞—Ñ–æ–Ω ‚Äî –æ–ø–µ—Ä–∞—Ç–æ—Ä –Ω–æ–º–µ—Ä 1 –≤ –†–æ—Å—Å–∏–∏!"
  mMHeader: "–í—ã –æ–±—Ä–∞—Ç–∏–ª–∏—Å—å –≤ OSS ESB.\n–ú–µ–≥–∞—Ñ–æ–Ω ‚Äî –æ–ø–µ—Ä–∞—Ç–æ—Ä –Ω–æ–º–µ—Ä 1 –≤ –†–æ—Å—Å–∏–∏!"
  mMGreetingButton: "–°–ª–∞–≤–∞ ESB!"
  mMGreetingAnswer: "–ú–µ–≥–∞—Ñ–æ–Ω—É —Å–ª–∞–≤–∞, %s!"
  mMWhoIsTheBossButton: "–ö—Ç–æ –ª—É—á—à–∏–π —Ç–∏–º–ª–∏–¥ –Ω–∞ –ø–ª–∞–Ω–µ—Ç–µ?"
  mMWhoIsTheBossAnswer: "–†–∞–∑—É–º–µ–µ—Ç—Å—è, –ª—É—á—à–∏–π —Ç–∏–º–ª–∏–¥ –Ω–∞ –ø–ª–∞–Ω–µ—Ç–µ - —ç—Ç–æ –ü–∞—à–∫–µ–≤–∏—á –û–ª—å–≥–∞"
  mMWhoIsYourDaddyButton: "–ö—Ç–æ —Ç–≤–æ–π –ø–∞–ø–æ—á–∫–∞?"
  mMWhoIsYourDaddyAnswer: "–ú–µ–Ω—è —Å–æ–∑–¥–∞–ª —ç–∫—Å–ø–µ—Ä—Ç —Ä–∞–∑—Ä–∞–±–æ—Ç–∫–∏ –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏–æ–Ω–Ω—ã—Ö —Ä–µ—à–µ–Ω–∏–π OSS ESB –°–º–∏—Ä–Ω–æ–≤ –ò–≤–∞–Ω a.k.a. HippoMaru"
  rKBHeader: |
    *–ü—Ä–∏–≤–µ—Ç, %s\!* üëã
  
    –ö–æ–º–∞–Ω–¥—ã\:
    ‚Ä¢ */start* \- –ø–µ—Ä–µ–∑–∞–ø—É—Å–∫ –±–æ—Ç–∞  
    ‚Ä¢ */menu* \- –≥–ª–∞–≤–Ω–æ–µ –º–µ–Ω—é  
    ‚Ä¢ */cat* \- —Å–∞–º—ã–µ —Å–æ—á–Ω—ã–µ –∫–∏—Å–∫–∏ üê±
  
    –í—Å–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º—ã–µ –∫–Ω–æ–ø–∫–∏ –ø—Ä–∏–ª–µ–ø–∏–ª –∫ —á–∞—Ç—É\.  
    –ü—Ä–∏—è—Ç–Ω–æ–≥–æ –ø–æ–ª—å–∑–æ–≤–∞–Ω–∏—è –±–æ—Ç–æ–º\! üòé
  rKBMainMenuButton: "–ì–ª–∞–≤–Ω–æ–µ –º–µ–Ω—é"
  rKBRandomCatButton: "–ú–Ω–µ –±—ã –∫–∏—Å–∫—É..."
  rKBRandomCatStarted: "–û–∫, —É—à—ë–ª –∏—Å–∫–∞—Ç—å –¥–ª—è —Ç–µ–±—è –∫–∏—Å–æ–Ω—å–∫—É"
  rKBRandomCatFinished: "–ù–∞—à—ë–ª! Sweet pussy, –Ω–µ —Ç–∞–∫ –ª–∏? )))"

url:
  randomCatImage: "https://api.thecatapi.com/v1/images/search"